### ISSUE TITLE
Rename `LayoutModifier` to `Modifier`

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#1047]
We don't want to go full Compose UI `Modifier`, but we also think that want to use this as a mechanism to globally attach some properties to all widgets (such as stable IDs, accessibility information, etc.). Additionally, it would let users attach metadata globally.

We talked about this back in February and agreed to do it. This is a tracking issue for following through on it.

**Comment by JakeWharton** [comment]
Might want to drop it into a `modifier` package since we'll presumably have global modifiers like stable ID and accessibility to put in there too.

**Comment by chrisbanes** [comment]
I'll take this. Should be fairly quick
