### ISSUE TITLE
Introduce `RedwoodView`

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#1116]
This is similar to `TreehouseView` but at the Redwood layer.

As `HostConfiguration` is moving to be within Redwood (#1054), we need the machinery that automatically monitors configuration changes and sends them into the composition to be turnkey code.

It _might_ be possible to eliminate `TreehouseView` as a result in favor of a smaller decorator around a `RedwoodView`.

**Comment by swankjesse** [comment]
Yes please. I think we could potentially nuke `TreehouseView` by moving its responsibilities to `Content`.

**Comment by veyndan** [comment]
Introduced in https://github.com/cashapp/redwood/pull/1435.
