### ISSUE TITLE
Mechanism for widgets to process a batch of changes

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#1133]
In LazyColumn when the scrolling window moves down by _N_ we perform many changes as a unit:

 * Increment `itemsBefore` by _N_
 * Remove _N_ elements from the start of `items`
 * Add _N_ elements to the end of `items`
 * Decrement itemsAfter by _N_

If we perform each of these changes independently, we have two bad options:

 * Janky scrolling behavior, because we send unnecessary ‘insert’ and ’remove’ events (#1127)
 * Inefficient native binding, because we signal that the entire dataset has changed (#1128)

A fix would be for Redwood to signal ‘the current batch of changes is complete’ to widgets like `LazyList`. It could in turn defer notifying its adapter until it can do so precisely.

This strategy could be also enable optimizations in other widget types. For example, an `Image` widget that has both a baseUrl and size property should build & fetch its Thumbor URL only once when both properties are change.

**Comment by veyndan** [comment]
Considering the `LazyList` example in isolation, what about just sending over the `itemsBefore`, `itemsAfter`, and `itemCount` wrapped in a data class?

```kotlin
data class ItemSnapshotList(
  val itemsBefore: Int,
  val itemsAfter: Int,
  val itemCount: Int,
)
```

**Comment by swankjesse** [comment]
Here’s one potential approach by knowing that the main dispatcher has a single queue.

```
class RealIcon : Icon {
  var scheduled = false
  lateinit var size: Size
  lateinit var url: String

  override fun setSize(size: Size) {
    this.size = size
    kickOffDownloadLater()
  }

  override fun setBaseUrl(url: String) {
    this.url = url
    kickOffDownloadLater()
  }

  fun kickOffDownloadLater() {
    if (scheduled) return
    scheduled = true
    postToMainThread {
      scheduled = false
      kickOffDownload(size, url)
    }
  }

  private fun kickOffDownload(size: Size, url: String) {
    ...
  }
}
```

**Comment by swankjesse** [comment]
Another approach. Add this to Redwood:

```
interface ChangeSetListener {
  fun beginChanges()
  fun endChanges()
}
```

Then widgets implement like so:

```
class RealIcon : Icon, ChangeSetListener {
  lateinit var size: Size
  lateinit var url: String

  override fun setSize(size: Size) {
    this.size = size
  }

  override fun setBaseUrl(url: String) {
    this.url = url
  }

  override fun beginChanges() {
  }

  override fun endChanges() {
    download(size, url)
  }
}
```

**Comment by JakeWharton** [comment]
We decided on the second approach, but only an end signal.

**Comment by JakeWharton** [comment]
We also tentatively decided that changes to direct children would get the callback, too. 

Although it's possible we may want to alter that simply because it's not a ton of information whereas we could offer something on each set of children instead. It's also worth thinking about how this ties in with modifier changes and their notifications to their parent children.

**Comment by JakeWharton** [comment]
Another wrinkle is how we support this in pure Redwood. With Treehouse it's trivial. With Redwood there is very little abstraction which provides the hooks necessary for such a callback.
