### ISSUE TITLE
Recycle widget instances

### ISSUE THREAD

**Issue by veyndan** [cashapp/redwood#1137]
Currently, platform-specific implementations of `LazyList` (e.g., `ViewLazyList`) don't recycle widgets. Instead of limiting the benefits of recycling to `LazyList`, we could instead make _all_ widgets recyclable.

This recycling should happen at the widget factory level. As soon as a widget is detached from the window, it should be added to a widget pool. When a widget is requested, we should check whether there is an available widget in the widget pool, otherwise create a new widget.

One thing I'm unsure about is whether we should be exclusively recycling the platform-specific representation of a `app.cash.redwood.widget.Widget` (e.g., `android.view.View`), or whether we should recycle the whole `app.cash.redwood.widget.Widget`.

**Comment by veyndan** [comment]
The docs of [`ReusableContent`](https://developer.android.com/reference/kotlin/androidx/compose/runtime/package-summary#ReusableContent(kotlin.Any,kotlin.Function0)) looks promising. Potentially an interesting alternative to recycling at the widget factory level.

**Comment by swankjesse** [comment]
I’m implementing general-purpose widget recycling in the widget-side `ProtocolBridge`. I’ve done a little exploration work and I’ve come up with a plan that I like...

### Reuse IDs

In a compositions we can express a reuse ID for an arbitrary widget. I’ll start with this as a `String?` (though it could be any compact identifier). The `reuseId` is a reserved property like `id` and `modifier`. It cannot be used as a property name in user-declared schemas.

Here’s what a typical usage will look like:

```kotlin
LazyColumn {
  items(dinosaurs) { dinosaur ->
    Row(reuseId = "dino") {
     Text(dinosaur.period)
     Text(dinosaur.name)
     Image(dinosaur.imageUrl)
    }
  }
}
```

Though `LazyColumn` is likely to be the most typical use-case, this mechanism is independent of `LazyColumn`. This is an equally-valid use of `reuseId`: 

```kotlin
Column {
  if (canToggleRed) {
    Row(reuseId = "colorToggle") {
     Text("Red")
     Checkbox(...)
    }
  } else {
    Row(reuseId = "colorLabel") {
     Text("Red")
    }
  }

  if (canToggleBlue) {
    Row(reuseId = "colorToggle") {
     Text("Blue")
     Checkbox(...)
    }
  } else {
    Row(reuseId = "colorLabel") {
     Text("Blue")
    }
  }
}
```

In the above example we have two pools of reusable widgets: `colorToggle` and `colorLabel`. The widgets may be added to the pool on one screen and retrieved from the pool on another.

I will need to update our codegen to support reuseIds. Every widget will have a reuse ID property, though I expect it will be used rarely.

### Policy for Reuse IDs

Reuse IDs should be constants in the code. Updating a reuse ID for an existing widget is undefined.

It is forbidden for a widget and any of its ancestors to both declare a non-null reuse ID. This will result in undefined behavior.

The pool size for each reuse ID is initially hardcoded to 20 on the host. This is enough to get a good benefit from the feature, and unlikely to create memory pressure.

The target use case for reuse IDs is on the immediate children of a `LazyColumn`. We will optimize for cases where these widgets are moderately complex: 0–20 child widgets in shallow subtrees.

Our initial implementation will only perform reuse when the _shape_ of the outgoing widget and incoming widget are the same. The shape of two widgets is the same if:
 * They have the same widget tag 
 * They have the same number of children in each slot
 * The paired up children have the same shape, recursively
Subtree shape doesn’t care about properties or modifiers.

The developer may declare widgets that have different shapes. This is not an error but may result in less reuse.

### Reuse Events

We’ll define an interface not unlike `ProtocolMismatchHandler` to add observability to view recycling.

```
interface ProtocolBridgeListener {
  fun onReuseSuccess(reuseId: String)
  fun onReuseFailedShapeMismatch(reuseId: String)
}
```

A developer that observes too many mismatches may chose to split their reuse ID into different cases.

### Implementation

This goes in `ProtocolBridge`. Roughly I think the new behavior will work like this:

On `ChildrenChange.Remove`:
 1. Find the node.
 2. Add it to the pool if the `reuseId` is set.
 3. Trim the pool to size.

On `Create`:
 1. Skip if `reuseId` is not set. (Making it easy to check this on node create is why `reuseId` is special.)
 2. Remove a pooled element with the same reuse ID. Skip reuse if none is found.
 3. In rounds, collect all of the new widget’s children. Look for `ChildrenChange.Add` and `Create` changes.
    * If the new widget is getting a child that isn’t also new, skip reuse. (no listener call)
    * If any widget is has a `Move` or `Remove` change, skip reuse. (no listener call)
 4. Check for shape equality between the created and pooled widgets. If not equal, fail reuse. Call the listener.
 5. Remove all of the created widgets’ `Create` events from the changes list.
 6.  Remove all of the descendant widgets’ `Add` events from the changes list. Do not remove the `Add` that adds the reused widget to a slot on its parent; we still need that.
 7. Put the pooled nodes into the `nodes` map, using the IDs from the matched `Create` events.
 8. Reuse success! Call the listener.

**Comment by swankjesse** [comment]
This is done.
