### ISSUE TITLE
Support Delay in the iOS Zipline dispatcher?

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#1181]
We provide a CoroutineDispatcher that runs Zipline in the background on iOS. In order to customize the stack size it needs to use a platform API (`NSThread`) instead of something provided by Kotlin (`newSingleThreadContext()`).

By using a platform API we also lose out on implementing `Delay`. I prototyped this building off some pretty old `CFRunLoop` APIs. There’s prior art of using these APIs in Kotlin/Native’s [Dispatchers.kt](https://github.com/Kotlin/kotlinx.coroutines/blob/5f60f224505580579a7f14aacd0051c055c19dc5/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt).

The CFRunLoop API works a lot like Android’s `Looper`, but older and in C. It’s got some power features we need – we decide when the runloop runs! But because it’s such an old API I couldn’t find much documentation on it - the [header copyright](https://opensource.apple.com/source/CF/CF-368.28/RunLoop.subproj/CFRunLoop.h.auto.html) is from 1998!

**Comment by JakeWharton** [comment]
Should we close this now that we discovered it runs on the `Default` dispatcher?

**Comment by swankjesse** [comment]
Yep. We should reopen if a performance problem occurs in practice.
