### ISSUE TITLE
State saving should be available in Redwood

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#1259]
Not just Treehouse.

**Comment by veyndan** [comment]
An example use case would be being able to [persist the counter value in the counter sample app](https://github.com/cashapp/redwood/compare/veyndan/2023-10-06/counter-rememberSaveable).

**Comment by veyndan** [comment]
One approach to solving this is what is outlined in https://github.com/cashapp/redwood/pull/1410#issuecomment-1681542586.

**Comment by JakeWharton** [comment]
I am doing this
