### ISSUE TITLE
Rename the `margin` property to `padding` to better align with the actual spacing performed

### ISSUE THREAD

**Issue by veyndan** [cashapp/redwood#1260]
As @colinrtwhite mentioned at https://github.com/cashapp/redwood/issues/855#issuecomment-1593540122:

> [Margin] behaves as padding when passed as an argument to the Row/Column functions, but it applies margin to any child items that have margin added using `Modifier.margin()`.

The `margin` property on `LazyRow`/`LazyColumn` also acts like padding (https://github.com/cashapp/redwood/pull/1234#discussion_r1230997405).

**Comment by colinrtwhite** [comment]
I think we should probably update the components to apply that property as margin instead. Having `padding` as a property and `Modifier.margin()` isn't great from an API perspective.

The downside to moving the components to apply `margin` as real margin is that it will have to be applied on the native views and can't be applied on the `Node`.

**Comment by swankjesse** [comment]
Our layout widgets (Column, LazyColumn etc.) should use the word `margin`, and apply this space outside the bounds of their child widgets.

We may also add or support a cross-cutting `padding` attribute that applies within the bounds of the child widgets.

Both are useful!

**Comment by squarejesse** [comment]
Our Column and Row classes put the margins around the child-owned area, so it behaves more like a margin. No action at this time.
