### ISSUE TITLE
Add screenshots tests for lazy behavior of `LazyList` in Android Views

### ISSUE THREAD

**Issue by veyndan** [cashapp/redwood#1263]
Currently, there are some screenshots tests for `LazyList`, but those involve very few items, as the goal is alignment with `Row`/`Column` when few items are displayed.

Some things we should add tests for (I'll edit the list as I think of new things):

- [ ] Ensure placeholders are displayed when items are being fetched.
- [ ] If there aren't enough placeholders in the pool, fetch more and display them.
- [ ] As the `RecyclerView` is scrolled, only the items within the viewport (and some of the surrounding items) are kept in memory.
- [ ] When the `LazyList` is backed by a `PagingSource` that is updated, the `LazyList` should scroll to the top (assuming that `PagingSource#getRegreshKey` returns `null`).

Some of the implementation between `ViewLazyList` and `UIViewLazyList` could be shared, such that unit tests for one covers both.

**Comment by squarejesse** [comment]
We have screenshot tests for LazyList now.
