### ISSUE TITLE
Triggering scrolls from presenter

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#1275]
I’ve got some presenter code that would like to scroll its scrollable containers. I imagine APIs like this:
 * scrollToTop()
 * scrollToBottom()
 * scrollToItem(someIdentifier)

What’s annoying about these is they’re more like events than properties, but events that flow the opposite direction from our usual ones.

I could synthesize this with properties in a pinch.

**Comment by JakeWharton** [comment]
Since everything is fundamentally rooted in Compose, there's not really a mechanism by which you can do this. The closest is how Compose UI does scrolling, which is by allowing you to adjust scroll on the scroll state object either directly or via animation.
