### ISSUE TITLE
Allow arbitrarily serializable content within `rememberSaveable`

### ISSUE THREAD

**Issue by veyndan** [cashapp/redwood#1384]
Currently, `rememberSaveable` only allows a `MutableState<T>`, where `T` is one of the `JsonPrimitive` (`String`, `Boolean`, `Number`), `List<JsonPrimitive>`, or `Map<JsonPrimitive, JsonPrimitive>`. If you want to serialize anything beyond that, we currently need to add explicit support for it in `StateSnapshot.kt`, and if it's a custom type, you're out of luck.

We should instead use the serializers provided by the user via their `Json` instance, so that the user can serialize anything they can write a serializer for.

```kotlin
Json {
  serializersModule = SerializersModule {
    contextual(CustomSerializer)
  }
}

object CustomSerializer : KSerializer<Custom> { … }

class Custom(val value: Int) { … }

rememberSaveable { Custom(42) }
```

**Comment by jingwei99** [comment]
> use the serializers provided by the user via their Json instance

This can be a good option. I think we need to talk over about the implications of this option (read: to serialize the whole Activity list feels pretty darn daunting for me at this moment, but maybe there are things I don't know so I'm over reacting)

**Comment by veyndan** [comment]
> read: to serialize the whole Activity list feels pretty darn daunting for me at this moment

I don't want to serialize the whole Activity list! I essentially want to implement a `Saver` similar to how [Compose UI saves scroll position](https://github.com/androidx/androidx/blob/a733905d282ecdba574bc5e35d6b0ebf83c82dcd/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/LazyListState.kt#L410-L421), which is serializing a couple of integers surrounded by a wrapper class.

**Comment by jingwei99** [comment]
oh that works!
