### ISSUE TITLE
On iOS, don't refresh all cells when items are inserted/removed

### ISSUE THREAD

**Issue by veyndan** [cashapp/redwood#1498]
When any property of `LazyList` changes on iOS, we invoke `collectionView.reloadData()`. This is an expensive operation which shouldn't be necessary to call, as we are given atomic change updates within `UICollectionViewListUpdateCallback`.

Currently, I don't have a lot of confidence in `UICollectionViewListUpdateCallback` being given the correct atomic change updates. This is due to the lack of tests, and the fact that on Android we invoke `notifyDatasetChanged` (the equivalent to iOS' `reloadData`) on a specific code path, further reducing trust that these atomic change updates are correct.

Therefore, I would argue that this is blocked by:

- [x] https://github.com/cashapp/redwood/issues/1497
- [x] https://github.com/cashapp/redwood/issues/1128

**Comment by swankjesse** [comment]
Implemented by https://github.com/cashapp/redwood/pull/1538
