### ISSUE TITLE
Android test app needs to handle some configuration changes

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#1517]
Probably just size change.

**Comment by ahmed3elshaer** [comment]
I would love to start working on this

**Comment by JakeWharton** [comment]
I actually did take a quick look at this and I think it will be entirely solved by #1518. We don't care about activity recreation so long as the app comes back on the same screen that you left.

**Comment by ahmed3elshaer** [comment]
Makes sense, I will do #1518 then, thanks for the heads up
