### ISSUE TITLE
Confirm we prioritize sendEvent() over sendFrame()

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#1540]
Imagine I’ve got a LazyList with 100 items and a user who wants to quickly scroll through em.

Here’s what I think the timeline might look like; times in milliseconds.

t=0: UI thread: Initial LazyList loaded window shows items starting at 0
t=100: UI thread: user scrolls to row 10, which triggers a call onViewportChanged(10, ...)
t=100: Zipline thread: receives the call to onViewportChanged(10, ...), and starts composing a new loaded with items starting at 10. This will complete in 200 milliseconds.
t=200: UI thread: user scrolls to row 20, which triggers a call to onViewport(20, ...)
t=300: UI thread: user scrolls to row 30, which triggers a call to onViewport(30, ...)
t=300: Zipline thread finishes the composition that starts at item 10.
t=300: UI receives the new loaded items that start at item 10.
t=300: Zipline thread: receives the call to onViewportChanged(20, ...), updates its state, and schedules a new composition. It doesn’t do any work yet.
t=300: Zipline thread: receives the call to onViewportChanged(30, ...) and updates its state only. The composition is still pending.
t=300: Zipline thread does a composition with the latest scroll window that starts at 30.

In this sketch I believe the Zipline thread will process all the inbound UI events before it begins a composition. I think we get this for free as a side-effect of compositions always running independent of state changes.

I’d like to confirm this is what actually happens. It would be a waste of compute to start a recomposition if there are unprocessed user interactions.

**Comment by underscoretang** [comment]
Just trying to work this out in my head: 

If we raise the amount of time that a composition takes to say 500ms just as an example with the same UI events.
```
t=300: Zipline thread does a composition with the latest scroll window that starts at 30
``` 
would complete at `t=1100` in this current model.

If we were able to cancel the inflight operation at
```
t=100: Zipline thread: receives the call to onViewportChanged(10, ...), and starts composing a new loaded with items starting at 10. This will complete in 500 milliseconds.
```
right when we receive 
```
t=300: UI thread: user scrolls to row 30, which triggers a call to onViewport(30, ...)
```
the operation we care about would finish at:
`t=800`

And if we have a lot of 
```
Zipline thread: receives the call to onViewportChanged(n, ...), updates its state, and schedules a new composition. It doesn’t do any work yet.
```
Wouldn't that have some impact on the inflight operation pushing it beyond 500ms?
