### ISSUE TITLE
Introducing a backgroundColor modifier

### ISSUE THREAD

**Issue by underscoretang** [cashapp/redwood#1541]
There's a very common need for applying a background color on a view that I think is a pretty universal need that might be worth promoting into redwood. 

This came out of working on `Box`. A familiar approach for debugging and building views (particularly around layout) is setting background colors for different views that you're trying to piece them together and position elements. This applies within redwood, but would also apply to folks building and composing a bunch of widgets together in a treehouse app as well. 

The representation of the color is up to debate but i'll just use hex for illustration

Having the ability to create a 
```kotlin
Row(
  width = Constraint.Fill,
  height = Constraint.Fill,
  horizontalAlignment = MainAxisAlignment.Center,
  verticalAlignment = CrossAxisAlignment.Center,
  modifier = Modifier.backgroundColor("#FF0000"),
) {
   Text("Hello:")
   Text("World")
}
```
would be a much more experience than:
```kotlin
Box(
  width = Constraint.Fill,
  height = Constraint.Fill,  
  horizontalAlignment = MainAxisAlignment.Center,
  verticalAlignment = CrossAxisAlignment.Center,
) {
  Rectangle( // Doesn't exist in redwood
    width = Constraint.Fill,
    height = Constraint.Fill,
    color = "#FF0000"
  )
  Row(
    width = Constraint.Fill,
    height = Constraint.Fill,
    horizontalAlignment = MainAxisAlignment.Center,
    verticalAlignment = CrossAxisAlignment.Center,
  ) {
    Text("Hello:")
    Text("World")
  }
}
```

There's a case to be made for `cornerRadius` as well, so I'd like to have a discussion of where these additional view attributes begin and end. Talked to @swankjesse about having some amount of common attributes that are available on web would be ideal.

**Comment by JakeWharton** [comment]
Today there is no mechanism to build such a thing. The feature request for the mechanism is tracked here: #1084. Adding first party background color decorator as part of that effort is probably safe.

**Comment by underscoretang** [comment]
Yup, this was meant to be a feature request. Can we track this separately as it's own issue. Same with the other's listed in that original ticket. The work is to add more modifier implementations for each of them right?

**Comment by JakeWharton** [comment]
Yeah we can track them separately and discuss their individual capabilities and merits.
