### ISSUE TITLE
Support `rememberSaveable` in Redwood-only apps

### ISSUE THREAD

**Issue by veyndan** [cashapp/redwood#1566]
Currently, `rememberSaveable` only works when using an instance of `TreehouseView`. Redwood-only apps still need the ability to persist values across configuration changes though. For example, [persisting the counter value in the counter sample app](https://github.com/cashapp/redwood/compare/veyndan/2023-10-06/counter-rememberSaveable) should be possible.

**Comment by JakeWharton** [comment]
I have this tracked at #1259. Your example is perfect, though. Can you add it there?
