### ISSUE TITLE
Crash in emoji-search after scroll position preservation commit

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#1604]
I haven't properly reviewed the PR yet, but I'm noticing a crash in Emoji Search after these changes:

- Run Emoji Search using Android Views
- Type "medal" into the search box
- Click on one of the medal emojis
- Press the system back button
- The app crashes with the exception `app.cash.zipline.ZiplineException: IllegalArgumentException: Failed requirement.`

_Originally posted by @veyndan in https://github.com/cashapp/redwood/issues/1599#issuecomment-1766197162_

**Comment by jingwei99** [comment]
looking!

**Comment by jingwei99** [comment]
So this crash happens when the list on screen (filtered search result) is shorter than the whole screen.
