### ISSUE TITLE
iOS snapshot metadata different for local vs. committed

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#1692]
Our iOS snapshot tool is emitting more PNG metadata than what we have in GitHub, and that is triggering unnecessary deltas on code changes. This occurs for me when running tests in Xcode 15.0.

The new metadata includes this extra line:

> Orientation **1 (Normal)**

### Before (currently on GitHub)
![Screenshot 2023-11-20 at 1 22 08 PM](https://github.com/cashapp/redwood/assets/133019/77327df0-2af2-455b-80ae-819c1db555dd)

### After (running tests locally)
![Screenshot 2023-11-20 at 1 21 58 PM](https://github.com/cashapp/redwood/assets/133019/481b66dd-e93a-4b1c-be4c-9a6ee846f46e)

**Comment by JakeWharton** [comment]
See https://github.com/cashapp/redwood/pull/1988#issuecomment-2077838600

Maybe fixed? Maybe not? Let me know.
