### ISSUE TITLE
Reserve obsolete tags

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#1801]
Sometimes we build a widget, deprecate it, and delete it. Even after it’s gone we never want to reuse its ID because old apps and old platforms might still be using it, and the failure mode will be confusing.

It’d be nice to have something like protobuf’s `reserved` mechanism to document IDs that are burned but not otherwise used.

**Comment by JakeWharton** [comment]
What about widget properties and children? Should those support reservation as well?

**Comment by JakeWharton** [comment]
It's easy to do this for widgets and children, so might as well.
