### ISSUE TITLE
`CodeListener` should not get `TreehouseView` parameter

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#1857]
There is no way to guarantee the `TreehouseView` subtype nor the type parameter type that is in use. Instead, the listener should capture the direct `TreehouseView` subtype instance directly. Through this it does not need a subtype cast, does not need to a type parameter cast, and will actually work with UI systems that do not support arbitrary external mutation (i.e., Compose UI and Swift UI).

**Comment by JakeWharton** [comment]
Note: This requires some work in our internal usage before it can be done.

**Comment by swankjesse** [comment]
Obsoleted by https://github.com/cashapp/redwood/issues/2174
