### ISSUE TITLE
Add row/col/box screenshot tests where we remove one modifier element from a child

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#1877]
Ensure the image changes as expected

**Comment by ahmed3elshaer** [comment]
Can we add these modifier removal test functions to the existing shared screenshot tests [AbstractFlexContainerTest](https://github.com/cashapp/redwood/blob/35bedbc6adcfe920201f484d14228e8c33b49fe9/redwood-layout-shared-test/src/commonMain/kotlin/app/cash/redwood/layout/AbstractFlexContainerTest.kt)?

**Comment by JakeWharton** [comment]
Yes. Although that doesn't cover Box.

I think we should actually switch to a completely empty Modifier not just remove one. Then every test should snap back to the same image.

**Comment by ahmed3elshaer** [comment]
What is the proper method for switching to an empty modifier? I tried `widget.modifier = Modifier` which results in different behaviors from ComposeUI and View.

For example when I created and recorded the following screenshot test inside [AbstractFlexContainerTest](https://github.com/cashapp/redwood/blob/35bedbc6adcfe920201f484d14228e8c33b49fe9/redwood-layout-shared-test/src/commonMain/kotlin/app/cash/redwood/layout/AbstractFlexContainerTest.kt) 
```kotlin
@Test
  fun testColumnWithChildModifierChanges() {
    testContainerWithChildrenModifierChanges(FlexDirection.Column)
  }

  @Test
  fun testRowWithChildModifierChanges() {
    testContainerWithChildrenModifierChanges(FlexDirection.Row)
  }

  private fun testContainerWithChildrenModifierChanges(
    flexDirection: FlexDirection,
  ) {
    assumeTrue(flexDirection in listOf(FlexDirection.Row, FlexDirection.Column))
    val container = flexContainer(flexDirection)
    container.width(Constraint.Fill)
    container.height(Constraint.Fill)

    val first = text(longText(), backgroundColor = Red)
    first.modifier = MarginImpl(30.dp)

    container.add(first)
    container.add(text(mediumText(), backgroundColor = Green))
    container.add(text(shortText(), backgroundColor = Blue))
    container.onEndChanges()
    verifySnapshot(container, "Assigned_Modifier")

    first.modifier = Modifier
    container.onEndChanges()
    verifySnapshot(container, "Empty_Modifier")
  }
```
`ComposeUI` outputs the expected screenshots, while `View` always outputs the screenshot with a margin applied, Note that I tried different modifiers and widgets and I get similar results
I feel that I'm missing something 😅 

| Platform | Assigned Modifier | Empty Modifier |
|--------|--------|--------|
| ComposeUI | ![app cash redwood layout composeui_ComposeUiFlexContainerTest_testColumnWithChildModifierChanges LTR_assigned_modifier](https://github.com/cashapp/redwood/assets/13245056/13d014bd-3378-4269-b80e-d3b0bb61f2ef) | ![app cash redwood layout composeui_ComposeUiFlexContainerTest_testColumnWithChildModifierChanges LTR _empty_modifier](https://github.com/cashapp/redwood/assets/13245056/b1295e63-3481-4b6c-ac9d-89fd754b997a) |
| View | ![app cash redwood layout view_ViewFlexContainerTest_testColumnWithChildModifierChanges LTR _assigned_modifier](https://github.com/cashapp/redwood/assets/13245056/22c94bd1-c7f8-49c0-86af-018a1585e18f) | ![app cash redwood layout view_ViewFlexContainerTest_testColumnWithChildModifierChanges LTR _empty_modifier](https://github.com/cashapp/redwood/assets/13245056/3e76b492-9589-421c-bb18-c64050ec8200) |

**Comment by ahmed3elshaer** [comment]
Also in [AbstractBoxTest](https://github.com/cashapp/redwood/blob/782de4a2e6a7ae236156d334e704a2959ae1abfa/redwood-layout-shared-test/src/commonMain/kotlin/app/cash/redwood/layout/AbstractBoxTest.kt) When I attempt to call `verifySnapshot(widget.value)` once with the modifier assigned and again when the modifier is emptied, I receive a crash from the `View` platform.

```
app.cash.redwood.layout.view.ViewBoxTest > testChildrenModifierChanges[RTL] FAILED
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5248)
        at android.view.ViewGroup.addView(ViewGroup.java:5077)
        at android.view.ViewGroup.addView(ViewGroup.java:5017)
        at android.view.ViewGroup.addView(ViewGroup.java:4989)
        at app.cash.redwood.layout.view.ViewBoxTest.verifySnapshot(ViewBoxTest.kt:69)
        at app.cash.redwood.layout.view.ViewBoxTest.verifySnapshot(ViewBoxTest.kt:33)
```
Test function 

```kotlin
@Test
  fun testChildrenModifierChanges() {
    val redColor = coloredText(MarginImpl(30.dp), longText(), Red)
    val widget = box().apply {
      width(Constraint.Fill)
      height(Constraint.Fill)
      children.insert(0, redColor)
      children.insert(1, coloredText(text = mediumText(), color = Blue))
      children.insert(2, coloredText(text = shortText(), color = Green))
    }
    verifySnapshot(widget.value)
    redColor.modifier = Modifier
    widget.children.onModifierUpdated(0, redColor)
    verifySnapshot(widget.value)
  }
```

**Comment by ahmed3elshaer** [comment]
@JakeWharton , sorry for bothering you with a lot of questions 🙏, Let me know if my approach with the test functions is what we need

**Comment by JakeWharton** [comment]
So it sounds like views are just broken today (which is the point of the tests!). We can file a separate bug about them not clearing state.
