### ISSUE TITLE
Reuse detection is accidentally quadratic

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#1924]
```kotlin
if (changes.subList(0, index).none { it is Create && it.id == change.id }) continue
```
We can walk backwards while `it.id == change.id` to look for a `Create`. No further. This should reduce the search space to a few indices at worst.

**Comment by swankjesse** [comment]
Unfortunately I worry that there could be an entire tree structure preceding it.

**Comment by JakeWharton** [comment]
In the protocol, create, properties, and modifiers for a single node are always grouped together, in that sequence. If you walk backwards and find any protocol change with a different ID then it's not a create.
