### ISSUE TITLE
redwood-lazylayout-dom artifact not being published in maven central version 0.9.0

### ISSUE THREAD

**Issue by niqo01** [cashapp/redwood#1925]
It looks like the artifact `redwood-lazylayout-dom` did not make it on maven central:
[https://search.maven.org/search?q=redwood-lazylayout-dom](https://search.maven.org/search?q=redwood-lazylayout-dom)

Probably because it's missing the gradle publishing directive here:
https://github.com/cashapp/redwood/blob/trunk/redwood-lazylayout-dom/build.gradle#L4

**Comment by JakeWharton** [comment]
Thanks. Want to send a PR? 0.10.0 goes out here in a few days. If not someone will get to it.

**Comment by JakeWharton** [comment]
This is actually intentional since it doesn't work right now. Adding behavior is tracked by #1048.
