### ISSUE TITLE
Optimize LazyList by using scroll direction to influence the loaded window

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#2002]
We currently load 15 items above and below the visible window. This is a simple strategy that mostly works, but there’s opportunities to make it more efficient:

 - Don't load items above when we're fling-scrolling down
 - Load already-requested items (the loaded window) in the current composition, _then_ load next-requested items in the next composition.

**Comment by dnagler** [comment]
Fixed in #2013!

**Comment by dnagler** [comment]
#2013 2013 was reverted in #2022--turns out the TODO we left should've been tackled in the same PR.

**Comment by dnagler** [comment]
Resolved with #2107!
