### ISSUE TITLE
Android: A widget with Modifier.flex() will do very bad things if nested inside of a Row + Column

### ISSUE THREAD

**Issue by ean5533** [cashapp/redwood#2018]
### Summary

On Android, putting an element with `Modifier.flex()` inside a Row which is inside a Column will do... strange things. It seems to shrink the Row's width to 0, and also somehow expands the height by some large amount.

Works as expected on iOS.

### Repro

```
Column {
  Row {
    Text("Some text", modifier = Modifier.flex(1.0))
  }
}
```

### Screenshots 
![image](https://github.com/cashapp/redwood/assets/1847776/68747e60-5031-4613-ab18-aa335acfe311)

### Attempted tweaks

* Works fine if using `Modifier.shrink` or `Modifier.grow` instead of flex

**Comment by JakeWharton** [comment]
Added a test-app screen for this in #2121
