### ISSUE TITLE
Column/Row margins do not change when updated

### ISSUE THREAD

**Issue by dellisd** [cashapp/redwood#2026]
```kotlin
Column(margin = Margin(start = if (thisOrThat) 16.dp else 0.dp)) { }
```

In this example, if `thisOrThat` is some state that mutates, the margins of this column don't get updated. This is especially noticeable in lazy columns with view reuse enabled.

**Comment by colinrtwhite** [comment]
We recently added [tests that reproduce this behaviour](https://github.com/cashapp/redwood/pull/1995). Interestingly the Compose UI implementation behaves as expected.

I've confirmed the correct margin is being passed to the Yoga implementation and a new layout pass occurs so the issue must be deeper inside the Yoga implementation. Looking...
