### ISSUE TITLE
Benchmark AndroidX bespoke collections vs JS built-in collections 

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#2074]
I suspect we're wasting a lot of cycles on these collections which help the JVM and native, but which hurt JS due to Long boxing and being user code vs intrinsics. Benchmark them on QuickJS and Node, and if the built-in ones are better let's send a PR to AndroidX to make the custom impls non-JS only.

In the JS I see scatter map and set, int int map and set, and int object map. Let's check 'em all.

**Comment by swankjesse** [comment]
Benchmarked and started a whole bunch of PRs to upstream repos.
