### ISSUE TITLE
Root component’s dimensions inconsistent across platforms

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#2128]
Here’s a composition with a label that draws wider than the screen.

```
    @Composable
    override fun Show(flow: CashFlow.Environment, scope: CoroutineScope) {
      Column(
        width = Constraint.Wrap,
      ) {
        Text("hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello ")
      }
    }
```

And here’s what that looks like on an iOS and Android device:
![Screenshot 2024-06-20 at 10 40 08 AM](https://github.com/cashapp/redwood/assets/133019/6a19faaa-2da1-44d7-a5d1-d3413912b584)

These should be the same.

**Comment by JakeWharton** [comment]
Related: #1859

**Comment by swankjesse** [comment]
Looking into this now. On iOS our root view doesn’t care if its child component’s dimensions exceed its own. Here I’ve got a label that’s 965px wide in a parent that’s 393px wide.

<img width="720" alt="Screenshot 2024-09-26 at 2 27 03 PM" src="https://github.com/user-attachments/assets/739be8b3-30e2-466c-85cd-3045faf4ce92">

**Comment by swankjesse** [comment]
# Root layout is pass-through

The root layout should be a pass-through layout:
 * On measure, it should forward its parent’s constraints down to its children.
 * On layout, its children should be forced to exactly match the parent.

I need to confirm we’re doing this on both platforms.

**Comment by swankjesse** [comment]
# Column(width = WRAP) is different between platforms

```
    Box(
      width = Constraint.Fill,
      height = Constraint.Fill,
    ) {
      Column(
        width = Constraint.Wrap,
      ) {
        Text(
          modifier = Modifier.margin(Margin(start = 350.dp)),
          text = "hello_world"
        )
      }
    }
```

On Android we don’t permit child components to exceed the columns’ own bounds.
On iOS we do.

### Android
<img width="423" alt="Screenshot 2024-09-26 at 3 29 35 PM" src="https://github.com/user-attachments/assets/890871fc-8c4b-447d-9331-9e2dfe229e13">

### iOS
![Simulator Screenshot - iPhone 15 simulator - 2024-09-26 at 15 30 44](https://github.com/user-attachments/assets/14e35580-d775-49f2-aa46-53dc3e9108c2)

We should pick one and be consistent.
