### ISSUE TITLE
Disposal callbacks aren't called when disposing of a TreehouseUi

### ISSUE THREAD

**Issue by dellisd** [cashapp/redwood#2248]
The following does not work when a TreehouseUi screen is closed/disposed of on both Android and iOS:
```kotlin
DisposableEffect(Unit) {
  println("Hello")
  
  onDispose {
    // Never called!
    println("World!")
  }
}
```

A workaround is to use a `LaunchedEffect`:
```kotlin
LaunchedEffect(Unit) {
  try {
    println("Hello")
    awaitCancellation()
  } finally {
    // This prints fine
    println("World")
  }
}
```

**Comment by JakeWharton** [comment]
If you are tearing down the whole Zipline instance, what's probably happening is that this is running after the binding through which logs are sent is removed.

**Comment by dellisd** [comment]
When you say Zipline instance, do you mean for a single screen?

My understanding was that a Zipline instance would survive for the lifetime of the treehouse _app_, but I'm seeing this issue when tearing down a single screen, e.g. navigating back from a treehouse screen.

**Comment by JakeWharton** [comment]
I don't know how it's wired internally, but I would expect each screen to be a Zipline instance, yes. I can look next week.

**Comment by swankjesse** [comment]
The Zipline instance spans multiple screens, so I think this is likely a lifecycle step I’ve missed in the Treehouse part of Redwood.

**Comment by swankjesse** [comment]
Fixed.
