### ISSUE TITLE
Split Column into scrolling and non-scrolling variants (and likewise for Row)

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#2370]
The host-side binding for `Column` is awkward because it must support dynamically changing from scrolling to not-scrolling, despite this not being a required use case in practice.

I’d like to split `Column` in two:

 * `ScrollVertically`: a wrapper widget with a single child and an optional callback for scroll actions
 * `Column`: like our existing Column, but locked to `Overflow.Clip`

For backwards-compatibility, we’ll maintain the old `Column` class (maybe called `LegacyColumn` or something), and do the work to make sure old hosts only see this one.

I’d like to do the same for `Row`.

**Comment by JakeWharton** [comment]
There is #2124 tracking this
