### ISSUE TITLE
[Emoji Search app] Sample is not working

### ISSUE THREAD

**Issue by vikaspw** [cashapp/redwood#2497]
I have run the Emoji search app ,  but changing compose view on Emoji Search on presenter logic is not reflecting on android/ios app ui. while server is running perfectly and able to detect changes, rebuild.
there is open issue - https://github.com/cashapp/redwood/issues/1820 is it linked with this?
is it not stable library ?

**Comment by JakeWharton** [comment]
Yes, this behavior is tracked by that issue. You can comment-out the `build.gradle` line which declares the embedded application if you want to do hot reloading. There is no timeline on for the fix–it's in an upstream library so it's out of our control. This doesn't affect the behavior of release builds so it's not a huge priority.

**Comment by vikaspw** [comment]
@JakeWharton But without can't we use this library for production app, as it seems network cache also not working, it always making calls to server and fetching screen data..
any suggestion here?

**Comment by JakeWharton** [comment]
I don't believe we have a network cache setup for Emoji, as it's primarily a development sample. In our production app we _only_ use a network cache. I will have to check tomorrow.

**Comment by vikaspw** [comment]
@JakeWharton How we can enable/setup network cache while using treehouse library.
We are thinking of using in production app, we can't go without network cache.
Please help

**Comment by vikaspw** [comment]
@JakeWharton Please suggest

**Comment by vikaspw** [comment]
@JakeWharton Did you make performance comparison between using treehouse library and without treehouse  library.
what is the overhead of using library?

**Comment by JakeWharton** [comment]
We have not, because nothing else really provides the capabilities that we're after.

Is Treehouse slower than just using native UI–absolutely. It _always_ will be. We work really hard on making the performance the best it can be given the capabilities that we want to offer. Being able to deliver layout changes to millions of users in under an hour rather than it taking two weeks is worth a slight hit on performance. These also aren't our most performance-sensitive screens in the app–those are still entirely native.

**Comment by vikaspw** [comment]
What about network cache...is it not supported by zipline?
Do we need to explicit set the cache control config?

**Comment by JakeWharton** [comment]
You have to set it up for each platform, but it has a default that should make it work automatically.

Android: https://github.com/cashapp/redwood/blob/trunk/redwood-treehouse-host/src/androidMain/kotlin/app/cash/redwood/treehouse/treehouseAppFactoryAndroid.kt#L36-L37

iOS: https://github.com/cashapp/redwood/blob/trunk/redwood-treehouse-host/src/iosMain/kotlin/app/cash/redwood/treehouse/treehouseAppFactoryIos.kt#L33-L34

**Comment by vikaspw** [comment]
@JakeWharton We already have design system , can we use compose multiplatform directly without using redwood and getting  advantage of update UI on the fly like server driven approach?
does protocol system work independently or we have to use redwood?

**Comment by JakeWharton** [comment]
You would have to define your design system in Redwood as a schema and create implementations of it for each platform. Redwood is generally designed for use with native UI, not cross-platform UI frameworks, although nothing would preclude you from implementing the design system interfaces once using multiplatform Compose UI. However then you would have to write all your screens using the Redwood composables and not Compose UI composables.

**Comment by vikaspw** [comment]
@JakeWharton So We have to use Redwood composable  for dynamic behaviour, and for new widget/schema addition we have to dependent on play store release cycle?
in short we can't make independent screen on the fly (like replacing emoji schema with some other schema)  but can make changes in existing widget..
Is my understanding correct?

**Comment by JakeWharton** [comment]
That is correct, yes.

**Comment by vikaspw** [comment]
@JakeWharton as you guys already shipped the cash app with tree house.. can you open source basic widget component of redwood composable like TextView, Button,Toolbar etc..
I hope you have developed these things already and will be helpful for us (not repeating the same thing)

**Comment by JakeWharton** [comment]
No, because it's specific to our design system and is not customizable. You can look at the basic schemas for our samples or the test app, and #2275 will offer a basic, blueprint-like set to experiment with. Part of the point is that we do not want to be prescriptive about how granular or coarse your design system schema is built. It's entirely up to you.

**Comment by vikaspw** [comment]
@JakeWharton Hi,
when i implement redwood design system interface in the compose multiplatform , i am facing issue -
FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: com.physicswallah.pwredwood.android, PID: 22010
                                                                                                    java.lang.ClassCastException: com.physicswalah.composesharedui.ComposeUiText$value$1 cannot be cast to kotlin.jvm.functions.Function2
                                                                                                    	at app.cash.redwood.widget.compose.ComposeWidgetChildren.Render(ComposeWidgetChildren.kt:40)
                                                                                                    	at app.cash.redwood.widget.compose.ComposeWidgetChildren.Render$lambda$1(Unknown Source:6)
                                                                                                    	at app.cash.redwood.widget.compose.ComposeWidgetChildren.$r8$lambda$ZMh4wg5ZuAVTn2LFd2ZHUZ3BkCU(Unknown Source:0)
                                                                                                    	at app.cash.redwood.widget.compose.ComposeWidgetChildren$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)

----------------
while same thing working fine when i use android compose ui.
could you please help here

**Comment by JakeWharton** [comment]
Seems like you're missing `apply plugin: 'org.jetbrains.kotlin.plugin.compose'
` from that module which configures the Compose compiler. It is required in every module which contains a `@Composable` function or lambda.
