### ISSUE TITLE
Upstream reusable row/col/box layouts into Redwood module

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#328]
These are foundational things that no one wants to build. Plus it would simplify our samples.

**Comment by colinrtwhite** [comment]
@JakeWharton Is the plan still to implement these in `commonMain`? In existing samples we use native bindings to create these widgets. Also should these live in `redwood-runtime` or `redwood-widget-compose`?

**Comment by JakeWharton** [comment]
Yes. We have a multiplatform paging library that we need to get over the finish line (cc @veyndan) and then it comes down to designing how building the integration into Redwood works.

My original idea was to have a widget which used events to communicate back to the composable when we reach half way to the end of a page so that it could load the next page in that direction. That would re-deliver the list of items back to the UI with the additional data. If you scroll too fast we would have to put placeholders into the UI while waiting for the data.

In the talk I designed the API basically the same way as Compose UI:
```kotlin
@Composable
fun MessageList(messages: List<Message>) {
    LazyColumn {
        items(messages) { message ->
            MessageRow(message)
        }
    }
}
```
We'll know the number of items so we can send that to the UI on first load which will power the `RecyclerView` / Compose UI `LazyColumn` / `UITableView` along with the first page of data. Then, as you scroll, the widget requests more pages which the composable uses to execute the item lambda for those items and then we add those to the list and send it back to the UI to be bound.

But we have basically nothing implemented at the Redwood layer so that's all a guess as to how it can work.

**Comment by veyndan** [comment]
> We have a multiplatform paging library that we need to get over the finish line (cc `@veyndan`) and then it comes down to designing how building the integration into Redwood works.

The priority is currently:

1. Get pagination and `LazyColumn` working internally. The Treehouse `LazyColumn` implementation is helping me refine the best workaround for many of the KMP issues that I'm facing (the issues have already been filed).
2. I'll then work on a public release of multiplatform-paging, and then a public release of `LazyColumn` within Treehouse. Granted that there's nothing technical preventing a public release of multiplatform-paging — just time and priority.

Obviously can rejig the priority if it makes sense.

> My original idea was to have a widget which used events to communicate back to the composable when we reach half way to the end of a page so that it could load the next page in that direction. That would re-deliver the list of items back to the UI with the additional data. If you scroll too fast we would have to put placeholders into the UI while waiting for the data.

My current prototype sends down a serialized instance of `androidx.paging.Pager`. This works around a couple of issues with just doing incremental paging loads based on scroll position:

1. Can do page jumping for free. We don't need to iterate through every page to the new scroll position, or have to create our own mechanism for skipping those iterations.
2. Super fast scrolling isn't expensive. By doing iterative page loading we'd need to load each page, but using `Pager`, it can skip page loads if need be.

> In the talk I designed the API basically the same way as Compose UI:

I'm still refining this side of things. I have a different API for it, but whatever Compose UI does is definitely the north star.

> We'll know the number of items so we can send that to the UI on first load which will power the RecyclerView / Compose UI LazyColumn / UITableView along with the first page of data.

By just serializing the Pager, we don't need to tell the UI how many items there are in the list. Internally this isn't crazy useful, but I can easily imagine not knowing the item count to be a common enough constraint.

> But we have basically nothing implemented at the Redwood layer so that's all a guess as to how it can work.

We have a fair amount, just none of it's public yet 😬

**Comment by JakeWharton** [comment]
Closing since we have this now. Ongoing bugs and features for it can be tracked on their own.
