### ISSUE TITLE
missing enableFeaturePreview('VERSION_CATALOGS') in settings.gradle

### ISSUE THREAD

**Issue by beyondeye** [cashapp/redwood#344]
It is missing and gradle is complaining (stop build with error)

**Comment by JakeWharton** [comment]
Version catalogs are stable as of Gradle 7.4: https://docs.gradle.org/7.4/release-notes.html#promoted

This is the current version of our Gradle wrapper. Ensure you are using our Gradle wrapper and not a system installation of Gradle.
