### ISSUE TITLE
Make protocol values all value types

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#418]
~There's no reason to use signed values.~ Just going to use value types instead. Unsigned values inside value types bad. See below..

**Comment by JakeWharton** [comment]
I can't tell if this is worth it or not. It's slightly more code because Kotlin has semi-lame coercion rules, but I think it's probably worth it.

**Comment by JakeWharton** [comment]
Actually seems like value classes might make the most sense. No one should be doing math on these. And one's value cannot be used for another (and we've had a bug or two on this in the past).

We can retain the use of ints in the schema definition and then have conversion functions to the value classes where ranges are validated.

**Comment by JakeWharton** [comment]
I have managed to convince myself that this is all a bad idea.

We want two things: value types to differentiate between the semantic meaning of each value and unsigned values so that the range is entirely positive. The problem is that unsigned types box during _both_ serialization and deserialization.

Consider this type:
```kotlin
@JvmInline
@Serializable
value class PropertyTag(val value: UInt)
```

Let's look at the generated serializer:
```js
  $serializer.prototype.serialize_pzq1au_k$ = function (encoder, value) {
    var tmp0_inlineEncoder = encoder.encodeInline_8gn4q6_k$(this.descriptor_1);
    if (tmp0_inlineEncoder == null)
      null;
    else {
      tmp0_inlineEncoder.encodeSerializableValue_bps9ot_k$(UIntSerializer_getInstance(), new UInt(_PropertyTag___get_value__impl__y7w42g(value)));
    }
  };
```
Ignoring the encode bit, we first call `_PropertyTag___get_value__impl__y7w42g` with the value which "unwraps" the value. This is an identity function because the value is already the underlying type.
```js
  function _PropertyTag___get_value__impl__y7w42g($this) {
    return $this;
  }
```
But then we immediately call `new UInt` with that value which allocates an object only to pass it to `UIntSerializer` (which will unwrap and serialize the value).

Similarly, in the deserialization path:
```js
  $serializer.prototype.deserialize_2wnycf_k$ = function (decoder) {
    return _PropertyTag___init__impl__yg2cb0(decoder.decodeInline_k1q7ba_k$(this.descriptor_1).decodeSerializableValue_xpp80o_k$(UIntSerializer_getInstance()).data_1);
  };
```
We again use `UIntSerializer` to get a `UInt` object and then immediately call `.data_1` to unwrap its value. We then pass that to our value "constructor" `_PropertyTag___init__impl__yg2cb0` but it re-boxes the value into a `UInt` 🤦 
```js
  function _PropertyTag___init__impl__yg2cb0(value) {
    new UInt(value);
    return value;
  }
```

At the very least, I am reverting all the unsigned stuff. There's no reason for a tag to go above 2^31. If you create 2^31 instances of widgets and wrap around to -2^31 for IDs then that is totally fine. The values are arbitrary anyway.

**Comment by colinrtwhite** [comment]
@JakeWharton Oof I'm guessing this affects all value classes that wrap another value class? Is it worth filing an issue with kotlinx.serialization?

**Comment by JakeWharton** [comment]
Yeah I'm going to ask them about it. Need to get around to making a self-contained demo.
