### ISSUE TITLE
LayoutModifiers with multiple scopes fail to generate.

### ISSUE THREAD

**Issue by colinrtwhite** [cashapp/redwood#459]
The following fails to build because impl classes are generated for both scopes which creates a redeclaration issue:

```kotlin
@LayoutModifier(1, scopes = [RowScope::class, ColumnScope::class])
public data class GrowLayoutModifier(
  val value: Int,
)

@LayoutModifier(2, scopes = [RowScope::class, ColumnScope::class])
public data class ShrinkLayoutModifier(
  val value: Int,
)
```

Generating the impl classes once and putting them in one file should fix this.

**Comment by colinrtwhite** [comment]
Going to take a quick stab at this.

**Comment by JakeWharton** [comment]
Yeah the scope stuff was kinda rammed into the layout modifier codegen. It needs a good cleaning up anyway.
