### ISSUE TITLE
Default support for lambda properties and children properties.

### ISSUE THREAD

**Issue by colinrtwhite** [cashapp/redwood#482]
Should we support `@Default` for `@Property(1) () -> Unit` properties and `@Children(1) @Composable () -> Unit` properties?

Currently both ignore `@Default`: lambda properties always use `null` as a default and `@Children` must always be set.

The main use case I see for this is if you want an `@Children` property to be optional (i.e. `@Default("{}")`). It seems less useful for lambda properties, though might be still worth supporting for consistency?

**Comment by JakeWharton** [comment]
Seems fine. It's just a shortcut to a literal expression that goes in the generated code so I don't see any harm in giving users the power for consistency's sake.
