### ISSUE TITLE
Remove viewFactory from UIViewRedwoodLayoutWidgetFactory.

### ISSUE THREAD

**Issue by colinrtwhite** [cashapp/redwood#489]
`UIViewRedwoodLayoutWidgetFactory` currently accepts a `viewFactory: RedwoodUIScrollViewFactory` param that creates `UIScrollView` instances. This is a work-around as it's not (easily) possible to extend `UIScrollView` from Kotlin multiplatform code so we delegate the creation to Swift code.

This is a pretty inconvenient work-around and we should figure out a way to remove the `viewFactory` param and create `UIScrollView`s without an external factory.

**Comment by colinrtwhite** [comment]
Related Kotlin issue: [KT-40426](https://youtrack.jetbrains.com/issue/KT-40426/Incorrect-Objective-C-extensions-importing-that-prevents-UIKit-usage)

**Comment by JakeWharton** [comment]
cc @kpgalligan

**Comment by colinrtwhite** [comment]
Spent some more time on this [here](https://github.com/cashapp/redwood/commit/00e4f2ccd790b04d4921ac5e4f5e0859097aec66) and I'm convinced it's not possible to solve this without the above compiler issue being fixed.

I was able to use the `cinterop` solution so that the `UIScrollView` methods can be overridden, however we can't call `super` for any other those methods, which is necessary for `layoutSubviews`.

**Comment by colinrtwhite** [comment]
Is it possible to somehow package Swift/ObjectiveC code in `redwood-layout-uiview`?

**Comment by JakeWharton** [comment]
With cklib, yes. At least according to Kevin. He was out last week but we'll talk on Tuesday about it. I'll invite you.

**Comment by colinrtwhite** [comment]
Awesome, thanks!
