### ISSUE TITLE
Add counter sample variant for Android + compose

### ISSUE THREAD

**Issue by dgmltn** [cashapp/redwood#490]
It might be nice to have a simple example with compose widgets instead of views, and to be able to compare the two.

(I've already done the work, but do you want it added to this repo?)

**Comment by JakeWharton** [comment]
Not sure whether we're going to keep the counter or not. Maybe just as an example of running natively on each platform (need to switch away from using the protocol).

We used to have a to-do sample that had both views and Compose UI but it wasn't really adding any value as a sample.

In either case, I'm happy to add this frontend to the counter regardless of whether we're going to keep it as a sample long-term or not.
