### ISSUE TITLE
Continue refactoring Treehouse APIs

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#513]
Follow up on comment https://github.com/cashapp/redwood/pull/416#discussion_r987960927 and https://github.com/cashapp/redwood/pull/509#issuecomment-1312320164. `ViewBinder` probably shouldn't be owned by the app but instead owned by the view hiearchy and `TreehouseView` since it operates on it.

**Comment by swankjesse** [comment]
Oooh I like that.

**Comment by swankjesse** [comment]
I’m gonna take this!

**Comment by swankjesse** [comment]
We’ve got two distinct responsibilities in `ViewBinder`:

 * Handle code-loading state callbacks
 * Produce a widget factory

The state loading callbacks aren’t very interesting and we could do them anywhere. Probably as a property on  a `CodeListener` of `TreehouseView`. I’ll send a first PR for this.

Offering access to the widget factory is trickier. It’s constrained in a few ways:
 * It wants to be created _after_ the `TreehouseApp`. In particular, `AndroidEmojiSearchWidgetFactory` uses the `TreehouseApp` to create rows dynamically.
 * It wants to be created for a particular `TreehouseView` on Android so it can get themes etc. from `Context`.

I’m also leaning to keeping `ProtocolMismatchHandler` app-scoped and not view-scoped. Right now it’s built from the `TreehouseApp` by adapting our new Treehouse-layer `EventListener`.

So I think we need the application-layer to pass something like this:
```
  public fun widgetFactory(
    app: TreehouseApp<*>,
    view: TreehouseView<*>,
    json: Json,
    mismatchHandler: ProtocolMismatchHandler,
  ): DiffConsumingWidget.Factory<*>
```

Perhaps we declare this exact function on `TreehouseApp.Spec` ?

**Comment by JakeWharton** [comment]
I think the whole `ViewBinder` interface should belong to the `TreehouseView` as-is. Then we can drop the `TreehouseView` argument since you can capture whatever you need from the view layer directly.
