### ISSUE TITLE
Use @ObjCName in Kotlin 1.8 to improve ObjectiveC/Swift interop

### ISSUE THREAD

**Issue by colinrtwhite** [cashapp/redwood#520]
Kotlin 1.8 comes with a new [`@ObjCName`](https://github.com/JetBrains/kotlin/blob/84650d08af34b1c23ce3ae5a758b8d98b3a06a46/libraries/stdlib/src/kotlin/annotations/NativeAnnotations.kt#L68) annotation that we can use to improve the names that are exposed to ObjectiveC/Swift code.

This should let us expose better names than `Redwood_layout_uiviewUIViewRedwoodLayoutWidgetFactory` and `Redwood_treehouseTreehouseApp`.

**Comment by JakeWharton** [comment]
We can do this now. We should do this now.
