### ISSUE TITLE
Split `TreehouseView`

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#541]
Currently it mixes two concepts which makes the API less-than-ideal:
- Functions for the app to control our implementations for Android views, Compose UI, and UIKit
   - `boundContent`
   - `hostConfiguration`
   - `children`
   - `reset()`
- Configuration and callbacks for the specific rendering
   - `widgetSystem`
   - `codeListener`

You can also tell that it's slightly weird because each view subtype should be able to force a specific type parameter for the widget factory but currently cannot.

I think `widgetSystem` and `codeListener` can be combined, and in the process some of the listener callbacks eliminated. Not sure what to call this type.

The others can stay together and exist only to bridge the app to the rendering layer but otherwise their APIs should never be seen by callers.

**Comment by JakeWharton** [comment]
Okay I started pulling on this thread and it's promising. But first it actually looks like there's some code-gen changes that would also help simplify Treehouse setup. Leaving until next week.

**Comment by swankjesse** [comment]
One quick note on combining `widgetSystem` and `codeListener` . . . in our current adoption there’s some TreehouseWidgetViews that use a loading spinner, and some that don’t. Both of these share the same widgets.

So wherever we land it shouldn’t be much work to configure the factory & loading spinner independently.

**Comment by JakeWharton** [comment]
Expanding on this more: the current design makes it nearly impossible to unit test `TreehouseView` subtypes. They're currently too smart, whereas we probably want them to be instantiable without a `TreehouseApp` and generally know nothing about the `A` type parameter. They're just focused on `W`.

I think what we want is a design where the `TreehouseView` subtype knows about the widget factory, has callbacks for lifecycle events, and exposes the `HostConfiguration` as a `StateFlow`. It's nothing but a very, VERY fancy `Button`. Or a much simpler `RecyclerView`. Just a UI node with no smarts.

Then, separately, you bind a `TreehouseView` to a `TreehouseApp` explicitly (rather than implicitly via constructor). This knows nothing of the `W` type parameter but only knows about `A`. It is also where you provide the `Content`. If you want to change the `Content` of an existing `TreehouseView` you re-`bind` it. If you want to bind an existing `TreehouseView` to new content you re-`bind` it.

This will make testing the `TreehouseView` subtypes simple. It will also make use in a recycled view situation easier. It should also mean the death of `WidgetSystem` and the re-injection of the `TreehouseApp` as a parameter. Recursive adapters for lazy column should be easier to create as a result.

**Comment by JakeWharton** [comment]
I'm not sure what this means for the automatic unbinding that currently occurs through the detach listener. I'm not sure how much we've actually ensured that behavior works in the UIKit and Compose UI variants of TreehouseView anyway...

I'm tempted to say that the act of binding should return a handle on a thing which unbinds, but it may not be strictly necessary if in fact the current mechanism works fine on all platforms.

**Comment by JakeWharton** [comment]
Okay I think we can do this slowly, starting with the first step of setting a `TreehouseApp` on a `TreehouseView` after it's constructed. The code used to be like this for one of the platforms, but was changed to normalize it with another. So we'll basically just flip that and normalize both to the other way.

That should unblock some unit testing of the `TreehouseView` subtypes which is a good first step.

**Comment by swankjesse** [comment]
Seeing the early fruits of this I really like it. In particular it suggests we could move TreehouseWidgetView all the way into Redwood (and perhaps rename it to say, RedwoodWidgetView?)

And that begins to make hooking features like widget recycling in a lot more approachable.

**Comment by swankjesse** [comment]
I’m taking a run at this. Here’s a sketch of what I’m going to attempt...

### Rename `TreehouseView.Content` to `TreehouseContentSource`

This _isn’t_ the content; it’s a thing that can produce the content via the TreehouseApp bridges. This type goes with the Zipline-side of the house that isn’t necessary for pure-redwood stuff.

### Create a new `Content` interface

This is the dynamic content that can populate a `TreehouseView`. This goes with the Redwood side of the house.

```
public interface Content {
  public fun bind(view: TreehouseView)
  public fun unbind()
}
```

Note that a single `Content` can be bound and unbound multiple times. It cannot be bound to multiple views simultaneously.

I can refactor our existing `RealBinding` class into the Treehouse implementation of this interface. And I can make `TreehouseApp` create these:

```
class TreehouseApp<A : AppService> {
  fun createContent(source: TreehouseContentSource<A>): Content
}
```

### Manage TreehouseView-Content bindings externally

I’ll remove the content fields from `TreehouseView`: `boundContent` and `content`. Instead I need hooks on `TreehouseView` to support an external binding. I’m using the term `readyForContent` below to abstract over what we currently do with the attached state.

```
interface TreehouseView {
  public var readyForContent: Boolean
  public var readyForContentChangeListener: ReadyForContentChangeListener

  public interface ReadyForContentChangeListener {
    public fun onReadyForContentChanged(view: TreehouseView)
  }
}
```

This will allow me to make an external function to coordinate the lifecycle of a `Content` and a `TreehouseView`:

```
public fun TreehouseView.bindWhenReady(
  content: Content,
) : Closeable {
  ...
}
```

Note that this doesn’t know about Zipline. But we can make an overload that does:

```
public fun <A : AppService> TreehouseView.bindWhenReady(
  app: TreehouseApp<A>,
  source: TreehouseContentSource<A>,
) : Closeable {
  ...
}
```

### Next Steps

If I’m able to land this, here’s what could follow:

 * `Content.preload()`: for Treehouse this starts the `TreehouseUi` composition before a `TreehouseView` has been assigned to it. We’ll need to buffer diffs! This should be useful for paging, where we want to load data (ie. diffs) asynchronously but display views synchronously.

 * Moving CodeListener to the Zipline side of the house.

 * Change `TreehouseView` to not depend on Zipline things.

 * Build a mechanism to create a `Content` from a `@Composable` function.

 * Make `LazyColumn` _optionally_ depend on Zipline things. It exposes `@Composable` functions, and either we directly convert them to `Content`, or we send ’em through `TreehouseContentSource`. I’m not yet really sure what this will look like.

**Comment by swankjesse** [comment]
### Before Closing This

 * [x] Eliminate `LoadingBinding` and the `Binding` interface.
 * [x] Make `RealBinding` a private class in `TreehouseContent.kt`.
 * [x] Moving `CodeListener` out of `TreehouseView` and into `TreehouseContent`.
 * [x] Drop type parameter on Content.

### Someday Maybe

 * Move `WidgetSystem` to `TreehouseApp.Factory` so callers don’t need to pass it in on every `createContent()` call?
 * Rename TreehouseView?
 * Move Content and TreehouseView to a different module?

**Comment by swankjesse** [comment]
No further action on this. Introducing `RedwoodView` is related.

https://github.com/cashapp/redwood/issues/1116
