### ISSUE TITLE
Ship a proper frame clock for Android

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#761]
The fixed 60 Hz clock isn’t right.

https://github.com/cashapp/redwood/blob/trunk/redwood-treehouse/src/hostMain/kotlin/app/cash/redwood/treehouse/ZiplineSession.kt#L37

See also, https://github.com/cashapp/redwood/issues/747

**Comment by JakeWharton** [comment]
We do ship one for Android already. I suspect what Treehouse needs to do is accept a `FrameClock` type so all of the existing, platform-specific ones can be used.

**Comment by swankjesse** [comment]
https://github.com/cashapp/redwood/pull/908

**Comment by JakeWharton** [comment]
#985
