### ISSUE TITLE
Allow host app to offer data to HostConfiguration

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#837]
Our application’s margins + padding etc. potentially vary by device screen size, and possibly also by release version.

It’d be nice to be able to pass a product-specific object with the HostConfiguration:

```
class CashAppStylesheet(
  val marginSmall: Int,
  val marginMedium: Int,
  val marginLarge: Int,
)
```

**Comment by swankjesse** [comment]
We can work around this by fetching this data via another mechanism.

**Comment by JakeWharton** [comment]
This seems like normal product-specific services which are provided to the Compose code. I don't think Redwood should be involved.
