### ISSUE TITLE
Parameterize usage of `TreehouseView`

### ISSUE THREAD

**Issue by veyndan** [cashapp/redwood#883]
I've just come into the case where I have a `CodeListener` and I want to do something with the `TreehouseView` argument of `CodeListener#onInitialCodeLoading(TreehouseView)`. This `TreehouseView` is _definitely_ a `TreehouseWidgetView`, as the host widgets are Android Views. At the moment, I have to cast the `TreehouseView` to a `TreehouseWidgetView` which feels icky and potentially prone to future runtime errors.

It'd be awesome if `TreehouseView` was a type parameter in `CodeListener`. This will probably result in this parametrization being propagated to many other places too.

**Comment by JakeWharton** [comment]
See #865. It is not safe to do this and it only works on Android views and not Compose UI or UIKit.

Ideally you are capturing the concrete instance of the view in some kind of listener and then using that to listen to code changes. The current design isn't one that will work long term.

**Comment by JakeWharton** [comment]
There's also direct arguments against this, for what it's worth. You could be driving two separate compositions with different UI toolkits within the same Zipline.

**Comment by veyndan** [comment]
@JakeWharton Are there any arguments against parametrising the `Widget.Children` within `TreehouseView`? It should work for Android Views, Compose UI, and UIKit.

```kotlin
public interface TreehouseView<W : Any> {
  public val children: Widget.Children<W>
  public val widgetSystem: WidgetSystem<W>
  public var readyForContentChangeListener: ReadyForContentChangeListener<W>?
  // etc.

  public fun interface ReadyForContentChangeListener<W : Any> {
    public fun onReadyForContentChanged(view: TreehouseView<W>)
  }

  public fun interface WidgetSystem<W : Any> {
    public fun widgetFactory(
      json: Json,
      protocolMismatchHandler: ProtocolMismatchHandler,
    ): ProtocolNode.Factory<W>
  }
}
```

Such a change would mean that `TreehouseView` could extend from `RedwoodView`.
