### ISSUE TITLE
Remove cklib workaround for extending UiView when updating to Kotlin 1.8.20.

### ISSUE THREAD

**Issue by colinrtwhite** [cashapp/redwood#893]
`1.8.20` enables a new strategy for [importing Objective-C extensions as class members in UIKit](https://kotlinlang.org/docs/whatsnew1820.html#import-objective-c-extensions-as-class-members-in-uikit). It's currently only enabled for NSView and UIView but that might be all we need. I haven't tested yet, but I think this should let us remove the cklib workaround for extending `layoutSubviews` in Kotlin code. Hopefully it also works for properties like `intrinsicContentSize`.

**Comment by JakeWharton** [comment]
Woah, nice. This and #742 can be done together, most likely.
