### ISSUE TITLE
Support for consumable host safe area insets

### ISSUE THREAD

**Issue by colinrtwhite** [cashapp/redwood#919]
Follow up from: https://github.com/cashapp/redwood/pull/913

Currently, we're exposing host safe area insets through `LocalHostConfiguration.current.safeAreaInsets`. Long term we'd like to use a different strategy, copying [Jake's comment](https://github.com/cashapp/redwood/pull/913#pullrequestreview-1388106302):

Long term, I think we should change the approach to be more like Compose UI. This would mean two things:

- The insets are available as their own composition local within pure Redwood (not Treehouse).
- The insets are consumable rather than static so that they reflect the composables position in the native UI toolkit view hierarchy.

Can we use the same API as Compose UI in Redwood? My first thought is we can't really use layout modifiers given the parent widget needs to understand them for them to have an effect.

**Comment by JakeWharton** [comment]
Yeah I'm not strictly tied to the exact Compose UI API–I actually don't even know what it looks like. More of the consumable mechanism that it uses and how it works within Compose, presumably through a composition local.

**Comment by chrisbanes** [comment]
Insets is tricky for anything multi-platform as Android has a million inset types (actually ~10) and other platforms have 1 (or zero). So we don't want to pollute the API just for the sake of Android being extremely granular.

A composition local could work here, but it would have slightly different guarantees to the way Android works. Consuming some insets would then stop them being 'dispatched' to children, but there's siblings to think about too. Off the top of my head, a composition local would mean that siblings would all get to consume some insets at the same level in the 'stack', which could lead to insets being applied multiple times. Probably fine but something to check.

**Comment by squarejesse** [comment]
This is done.
