### ISSUE TITLE
Build config: Update to use convention plugins

### ISSUE THREAD

**Issue by aSemy** [cashapp/redwood#966]
Hi, as part of trying to [diagnose an issue with Dokkatoo](https://github.com/adamko-dev/dokkatoo/issues/57) (see https://github.com/cashapp/redwood/issues/933) I refactored Redwood's build config to use Gradle convention plugins to configure the build.

Convention plugins have a number of advantages, and [using `allprojects {}` is discouraged](https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html#sec:convention_plugins_vs_cross_configuration).

The end-result is something that's more [Gradle idiomatic](https://github.com/jjohannes/idiomatic-gradle) and uses the Kotlin DSL to help with type-safety and auto-complete.

There are convention plugins for specific aspects that can be applied on a per-subproject bases.

<img width="989" alt="image" src="https://user-images.githubusercontent.com/897017/233976209-b19e9521-0f1a-40c5-8fbd-9fee6f6663a7.png">

And the root `build.gradle.kts` is very simple.

```kotlin
// ./build.gradle.kts

plugins {
  id("app.cash.redwood.buildsupport.conventions.base")
  id("app.cash.redwood.buildsupport.conventions.spotless")
  id("app.cash.redwood.buildsupport.conventions.publishing.dokka")
}
```

It's still a rough first attempt, but it's most of the way there. If you're interested, I could create a PR?

**Comment by JakeWharton** [comment]
I think that's a bit overboard on plugin granularity. The complexity of our build and the fact that there's a lot of variety in each project's configuration does not lend itself well to this structure.

When I've experimented with this in the past I've preferred a single plugin which exposes an extension that has a DSL specific to the features needed. This way the Gradle file of the project only applies a single plugin and then uses the DSL to enable features it needs.

**Comment by aSemy** [comment]
> I think that's a bit overboard on plugin granularity. The complexity of our build and the fact that there's a lot of variety in each project's configuration does not lend itself well to this structure.

Yes, I certainly agree, but it how I thought was best to match the existing config (which I didn't want to change) where some subprojects only applied some one target (like only JS, or macOS, or iOS). The main goal was to remove `allprojects {}` and to use [the Plugins DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block), while keeping the current config as-is.

If I did a second pass I'd try to merge a lot of the convention plugins.

**Comment by JakeWharton** [comment]
Your effort has inspired me to finally get my idea to land in the repo. I've started it in #1036. Turns out I actually had four old branches where I attempted to get this going but was unable to land. Going incrementally helped quite a bit and fifth was the charm.

Thanks for taking the time to help out here.
