### ISSUE TITLE
Change LazyColumn keys from String to Any?, handle nullable

### ISSUE THREAD

**Issue by swankjesse** [cashapp/redwood#972]
@chrisbanes, from the PR that added mandatory keys,

> I like the simplicity of String but is it better to leave the key type to the user? Tricky with serialization though. Also, having a null key is probably something we'd want to support?
>
> Compose UI supports this via an Any? type, which coaleces to the list index if null.

Supporting `Any?` is difficult with serialization, and potentially prone to runtime errors if the supplied type is not serializable. We’d need to do something polymorphic and pass the type name in.

Null is significantly easier.

**Comment by chrisbanes** [comment]
The nullable side of this is covered by #976. Being able to use `Any?` is a trickier as Jesse mentioned above.

Normally I'd say runtime crash is OK, but not for something where we send stuff over the wire. I'm happy to close this? @veyndan

**Comment by veyndan** [comment]
> Normally I'd say runtime crash is OK, but not for something where we send stuff over the wire.

I think I'm missing something. Why is it particularly worse to not crash when sending something over the wire vs a standard runtime crash?

**Comment by chrisbanes** [comment]
My thought is that it's harder to debug/rectify as there's the added complexity of what version is being used?

**Comment by swankjesse** [comment]
Obsolete. LazyLists no longer have keys!
