### ISSUE TITLE
EmojiSearch iOS app crashing on launch

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/redwood#989]
Can't find `AppLifecycle`. I closed Xcode and lost the trace, but it was a zipline mismatch exception or whatever they're called.

**Comment by swankjesse** [comment]
I believe this is caused by a stale code in the Zipline cache.

**Comment by JakeWharton** [comment]
Do we just disable the cache then? Rely only on the dev server for now, and eventually the bundled artifacts needed for UI tests.
